---
apiVersion: v1
kind: Secret
metadata:
  name: remote-kubeconfig
  namespace: ydb
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1ESXhOREE1TXpVeE1sb1hEVE0wTURJeE1UQTVNelV4TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS042CmdkeU9tOFg3UnloQlRORnlXdGlkNTBNOHV4MHAzUGRtUWNDejZna1dUQkxWN3ZKcTNhN0lkQU1iWFd5N1djaDgKSkEyK05ITGQ4WmlaMXhtczNJRW5kV0ovTlk2MW0vbU9TYWwrQWU4ekl4c0VpU2lqWVZiK2h6Um9hQW5vRUo1SApVdDJ3MHNjTHlQdDkwcEtyUEg3bVRnTXlpWWlkWkIvRE1zdVdrRmZoRXlSa0Y5N2FDVFNock1RVGx3VENWQ3pTClJBbjVGS3VaQ3JIL1A4N09obUYrcjE2clFxSk11ZStFKzlPUXV6RHpEa2toYXVFWHhhWmE5a1NtRVJtYm10ZUsKWUl2ZUxnWFN5Y01CaWlSREcyZS9MMzc2bHNpbVk4aFFORXBURUZiajBWeTVFem56SXdCOVJELzV6bVZaK2czQgpxd1NTdUk0MFBoVmVONzREc0xVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKdGpHVWZ1SFcyak1oZHlFWWpuWnhVOXE3eTBNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCZGpCcGJUZnp6R3FkU3YxZHBXcW1tM2pwU3pzUnVRZlRtVVhacFJEMzMyek5SY2JVRApKc04xc0dkVFhwTlpCbnlMVENzMXMrV2FIUFJUOTNpMCtETU12ZUpMVkE0MVM4VkgwWnBQVGt0MU1RZkVvb2U2CjdmL0psYU85T3lwbnRmSXI3cUc1aEVhd3A4VDVEL3ptMGttdGZXRHhJeXcyNDlFWWMwT1VrZ3BxalArdkpFRFIKUzc1S29vU2N1bEJMWkYrZ1pOSnF5SUdVUUpZcWhnT2thUlJoSG9Fa01XQ3IyNklIQWd3T2Zpd0ZROWIwaSt6WQo1dDZXcnR5Y2NvUkgxNjR0RThieVNGZkh0MCt3SkVrNWNZSm5UdUdjcVNKOEJ2Y20vbXFyN2NxWDZDT1kzM3FCClh0ZSsvUkszVDI5Y0hGbE9WK3Y4eXNiZFFsRkNWbHdDWGhuUAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://158.160.133.132
      name: yc-mgmt-dev
    contexts:
    - context:
        cluster: yc-mgmt-dev
        user: yc-dev
      name: remote
    users:
    - name: yc-dev
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im5nSGMzSk9ZWFZCNWhjTUZlVmt0NHFaNzV2b0xCcHU4VUxuOXNURFZPZkUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ5ZGIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoieWMtZGV2LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InljLWRldiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjJhYjkyYTM0LWNiZWQtNGFhNS05MTZlLTE2NTI0YzdmYjI4YyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp5ZGI6eWMtZGV2In0.pL_8YASyhLBGcchbWYYa1lhQOk859epKyCGu26z-orOjsoJmx6J1vTesHLno2Fa0tWSCDFYjDDAlL2D9OgO0fcXR9DHSv4NVJPiSkmCGXOGKi-eiGmLpuq8psQ1wUzcqMyfgDQE_E1FY4VUf2FxNA7YTa-sLswlki2zLpdYdowBX_uuejsRdbBKY7QMRMoL8pk5pbaqDYh3axAznAoCOyf7NoQniefjR_y71i4-3oV8JW2wlUqR8d2QiLvP_9fYYQIJARwrDZauoGF7awu-vJJoaJjKWH6jfXlFw0xyCSx4kK1Kkxfq1K1HjkI1M7bXNP9jv93zH-Q7gIE02n_3pnQ
    current-context: remote
type: Opaque
